apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-hostnw-sa
  labels:
    app: nginx
    type: madhav-psp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      hostNetwork: true
      serviceAccount: specialsa
      containers:
      - name: nginx
        image: nginx
